name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test Sinuka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Sinuka - Restore dependencies
      run: cd Sinuka && dotnet restore
    - name: Sinuka - Build
      run: cd Sinuka && dotnet build --no-restore
    - name: Sinuka - Test
      run: cd Sinuka && dotnet test --no-build --verbosity normal
    
  Test Mukamu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Mukamu - Restore dependencies
      run: dotnet restore
    - name: Mukamu - Build
      run: dotnet build --no-restore
    - name: Mukamu - Test
      run: dotnet test --no-build --verbosity normal