name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  E2ETest_Sinuka:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7.32'
          mysql database: 'sinukaka'
          mysql root password: 'root'
      - name: Update database
        run: |
          dotnet tool install --global dotnet-ef
          pwd
          ls
          cd Sinuka
          pwd
          dotnet tool restore
          dotnet ef database update 
      - name: Start Sinuka
        run: dotnet run --project ./Sinuka/src/Sinuka.WebAPIs
      - uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json

  UnitTest_Sinuka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Sinuka - Restore dependencies
      run: cd Sinuka && dotnet restore
    - name: Sinuka - Build
      run: cd Sinuka && dotnet build --no-restore
    - name: Sinuka - Test
      run: cd Sinuka && dotnet test --no-build --verbosity normal
    
  UnitTest_Mukamu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Mukamu - Restore dependencies
      run: dotnet restore
    - name: Mukamu - Build
      run: dotnet build --no-restore
    - name: Mukamu - Test
      run: dotnet test --no-build --verbosity normal