name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  E2ETest_Sinuka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7.32'
          mysql database: 'sinukaka'
          mysql root password: 'root'
      - name: Install Newman
        run: npm install newman -g
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef
      - name: Restore Sinuka
        run: cd Sinuka && dotnet restore 
      - name: Run migrations to DB
        run: cd Sinuka && dotnet ef database update --project ./src/Sinuka.Infrastructure
      - name: Insert Client Data
        run: sleep 10 && mysql -u root -proot -h 127.0.0.1 sinukaka -e "INSERT INTO Clients(Id, Name, Secret, CreatedAt, UpdatedAt, HostName) VALUES ('69a29c6d-80b1-4c7b-a08b-38c7a27aaf4d', 'TEST', 'TEST', NOW(), NOW(), 'TEST');"
      - name: Start Sinuka and Run E2E Tests
        run: |
          cd Sinuka && dotnet run --project ./src/Sinuka.WebAPIs &
          sleep 5
          cd Sinuka && newman run ./Sinukaka.postman_collection.json --insecure

  IntegrationTests_Sinuka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Sinuka - Restore dependencies
      run: cd Sinuka && dotnet restore
    - name: Sinuka - Build
      run: cd Sinuka && dotnet build --no-restore
    - name: Sinuka - Test
      run: cd Sinuka && dotnet test .\src\Sinuka.Tests\IntegrationTests\ --no-build --verbosity normal

  UnitTests_Sinuka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Sinuka - Restore dependencies
      run: cd Sinuka && dotnet restore
    - name: Sinuka - Build
      run: cd Sinuka && dotnet build --no-restore
    - name: Sinuka - Test
      run: cd Sinuka && dotnet test .\src\Sinuka.Tests\UnitTests\ --no-build --verbosity normal

  Test_Mukamu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Mukamu - Restore dependencies
      run: dotnet restore
    - name: Mukamu - Build
      run: dotnet build --no-restore
    - name: Mukamu - Test
      run: dotnet test --no-build --verbosity normal